const filters = {
  Chairs: [
    "chair",
    "armchair",
    "office chair",
    "dining chair",
    "rocking chair",
    "stool",
    "bench",
  ],
  Sofas: ["sofa", "couch", "sectional", "loveseat", "futon"],
  Tables: [
    "table",
    "coffee table",
    "side table",
    "dining table",
    "console table",
    "desk",
    "workstation",
  ],
  Beds: ["bed", "bed frame", "bunk bed", "daybed", "mattress", "headboard"],
  Storage: [
    "cabinet",
    "drawer",
    "dresser",
    "wardrobe",
    "closet",
    "shelf",
    "bookcase",
    "storage",
    "tv stand",
    "media unit",
  ],
  Lighting: [
    "lamp",
    "floor lamp",
    "table lamp",
    "ceiling lamp",
    "light",
    "lighting",
  ],
  Decor: [
    "mirror",
    "rug",
    "carpet",
    "clock",
    "vase",
    "plant",
    "frame",
    "cushion",
    "curtain",
    "decoration",
    "decor",
  ],
  Outdoor: ["outdoor", "garden", "patio", "balcony"],
};

export default filters;
